version: '3.7'

services:
  composer:
    image: composer
    command: composer install
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app

  php:
    image: php:7.4-fpm
    build: .conf/php/
    restart: always
    expose:
      - 9001
    volumes:
      - .:/app
      - .conf/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .conf/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - .conf/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /app

  phpunit:
    image: php:7.4-fpm
    volumes:
      - .:/app
    working_dir: /app

  fpm:
    image: php:7.4-fpm
    restart: always
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - .:/app
      - ./var/log/nginx:/var/log/nginx
      - .conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
